### PR TITLE
Added registrar-side communication with participants. More advanced communication coming soon

### PR DESCRIPTION
**Pull request by MrQuasar173**
Yeah I know there are three commits with nearly the same message don't pay attention to that.

### CODE REVIEW

**Review by IsaccBarker — COMMENTED** [review]
Shouldn’t the test message be moved inside the loop? That way you are always inside the “event loop”, and never have to break it. Putting it inside also means you can connect as many participants as nessisary.
Also, you shouldn’t put the event loop inside the constructor. Make a seperate member function named run or something

**Review by IsaccBarker — CHANGES_REQUESTED** [review]
Also, you forgot to call the tcp_init member function in the constructor

**Comment by MrQuasar173** [comment]
The constructer is empty...
Are you sure you're looking at the right file? I do everything in Registrar::run

**Comment by IsaccBarker** [comment]
Yeah, no I am. You are suppose to call initialization code in the constructor.

**Pull request closed without merging**
